apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: LoadBalancer
  selector:
    app: django
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | int }}
      targetPort: 8000