services:
    django:
        build:
            context: ./app
            dockerfile: ../infra/docker/django/Dockerfile
        environment:
            PRODUCTION: ${PRODUCTION}
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        command: >
            sh -c "
            pip list &&
            python -c 'import os; print(\"POSTGRES_HOST:\", os.environ.get(\"POSTGRES_HOST\"))' &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000
            "
        volumes:
            - ./app:/usr/src/app
        networks:
            - django_network
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:18.4-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
          - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql
        networks:
            - django_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            interval: 5s
            timeout: 5s
            retries: 5
    nginx:
        image: nginx:1.31-alpine
        ports:
            - "8080:80"
        volumes:
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - django_network
        depends_on:
            - django

volumes:
    postgres_data:

networks:
    django_network:
        driver: bridge