image:
  repository: "509086684760.dkr.ecr.us-east-1.amazonaws.com/lesson-8-9-ecr"
  tag: "7edf3bb"
service:
  type: LoadBalancer
  port: 80
hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
env:
  PRODUCTION: "True"
  ALLOWED_HOSTS: "*"
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
