namespace: djangoapp
image:
  repository: "509086684760.dkr.ecr.us-east-1.amazonaws.com/lesson-fp-ecr"
  tag: "237f836"
service:
  type: LoadBalancer
  port: 80
hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
env:
  PRODUCTION: "True"
  ALLOWED_HOSTS: "*"
  POSTGRES_PORT: "5432"
