image:
  repository: "509086684760.dkr.ecr.us-east-1.amazonaws.com/lesson-8-9-ecr/django-app"
  tag: "b50434b"
env:
  PRODUCTION: "True"
  ALLOWED_HOSTS: "*"
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
