apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  PRODUCTION: {{ .Values.env.PRODUCTION | quote }}
  ALLOWED_HOSTS: {{ .Values.env.ALLOWED_HOSTS | quote }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | quote }}