apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore

  target:
    name: rds-credentials
    creationPolicy: Owner

  data:
    - secretKey: host
      remoteRef:
        key: fp-rds-secret
        property: host

    - secretKey: port
      remoteRef:
        key: fp-rds-secret
        property: port

    - secretKey: dbname
      remoteRef:
        key: fp-rds-secret
        property: dbname

    - secretKey: username
      remoteRef:
        key: fp-rds-secret
        property: username

    - secretKey: password
      remoteRef:
        key: fp-rds-secret
        property: password